ALTER TABLE owners
ALTER COLUMN name TYPE VARCHAR(512);

ALTER TABLE jobs
ALTER COLUMN name TYPE VARCHAR(512);

ALTER TABLE datasets
ALTER COLUMN name TYPE VARCHAR(512);

ALTER TABLE namespaces
ALTER COLUMN name TYPE VARCHAR(512);
